{% set name = "intake" %}
{% set version = "0.6.2" %}
{% set sha256 = "b0cab1d185a703acb38eecb9cff3edd5cc7004fe18a36d5e42a8f7fffc9cca1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - entrypoints
    - jinja2
    - msgpack-python
    - numpy
    - pyyaml
    - requests
    - dask >=1.0
    # dask[bag]
    - cloudpickle >=0.2.2
    - fsspec >=0.6.0
    - toolz >=0.8.2
    - partd >=0.3.10

test:
  source_files:
    - intake
  imports:
    - intake
    - intake.auth
    - intake.catalog
    - intake.cli
    - intake.cli.client
    - intake.cli.server
    - intake.container
    - intake.gui
    - intake.source
  commands:
    - pip check
    - intake list --help
    - intake-server --help
  requires:
    - pip

about:
  home: https://github.com/intake/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system
